version: '3'

services:
  ebook-sender-bot:
    image: qcgzxw/ebook-sender-bot:latest
    container_name: ebook-sender-bot
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - APP_MODE=prod
      - MAX_SEND_LIMIT=10
      - FORMAT=epub
      - EMAIL_PROVIDER=config
      - DB=sqlite
      - DB_NAME=ebook-sender-bot
      #- DB=mysql
      #- DB_NAME=tg_bot_kindle
      #- DB_HOST=192.168.1.1
      #- DB_PORT=3306
      #- DB_USER=root
      #- DB_PASSWORD=root
      - SMTP_HOST=
      - SMTP_PORT=
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - BOT_TOKEN=
      - DEVELOPER_CHAT_ID=
    volumes:
      - ./ebooks/:/app/storage/
      - ./default.log:/app/default.log
